# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeSAC_Firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeSAC_Firebase

	pod 'Firebase/Analytics'
	pod 'Firebase/Crashlytics'
	pod 'Firebase/Messaging'

end
