# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeSAC_Week7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeSAC_Week7
	pod 'Toast-Swift', '~> 5.0.1'
	pod 'Alamofire', '~> 5.4'
	pod 'IQKeyboardManagerSwift'




end
